from ink2canvas.svg.Element import Element
from ink2canvas.svg.AbstractShape import AbstractShape
from ink2canvas.svg.Ellipse import Ellipse
from ink2canvas.svg.G import G
from ink2canvas.svg.GradientDef import GradientDef
from ink2canvas.svg.Line import Line
from ink2canvas.svg.LinearGradient import Lineargradient
from ink2canvas.svg.Path import Path
from ink2canvas.svg.Polygon import Polygon
from ink2canvas.svg.Polyline import Polyline
from ink2canvas.svg.RadialGradientDef import RadialGradientDef
from ink2canvas.svg.Circle import Circle
from ink2canvas.svg.Rect import Rect
from ink2canvas.svg.Text import Text
from ink2canvas.svg.Use import Use
from ink2canvas.svg.Defs import Defs
from ink2canvas.svg.ClipPath import Clippath